export default {
  SET_LOGO: "SET_LOGO",
  SET_SLIDER_PHOTOS: "SET_SLIDER_PHOTOS",
  SET_ERROR: "SET_ERROR",
  SET_FEATURE_PHOTOS: "SET_FEATURE_PHOTOS",
  SET_TESTIMONIAL_BACKGROUND: "SET_TESTIMONIAL_BACKGROUND",
  SET_LOADING:"SET_LOADING",
};
